include:
  - nginx-proxy-compose.yaml
services:
  server:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
      no_cache: true
    environment:
      - VIRTUAL_HOST=/run/secrets/virtual
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=/run/secrets/letsencrypt
      - TOKEN=/run/secrets/token
    secrets:
      - virtual
      - letsencrypt
      - token
secrets:
  virtual:
    file: ./secrets/virtual_host.txt
  letsencrypt:
    file: ./secrets/letsencrypt_host.txt
  token:
    file: ./secrets/token.txt