version: '3'
services:
  go-flashy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=flashy.academy
      - LETSENCRYPT_HOST=flashy.academy