include:
  - nginx-proxy-compose.yaml
services:
  server:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=/run/secrets/virtual
      - LETSENCRYPT_HOST=/run/secrets/letsencrypt
      - TOKEN=/run/secrets/token
      - COMPOSE_REMOVE_ORPHANS=1
    secrets:
      - virtual
      - letsencrypt
      - token
secrets:
  virtual:
    file: ./secrets/virtual_host.txt
  letsencrypt:
    file: ./secrets/letsencrypt_host.txt
  token:
    file: ./secrets/token.txt