include:
  - nginx-proxy-compose.yaml
services:
  server:
    restart: unless-stopped
    image: thestephenhunt/flashy
    environment:
      VIRTUAL_HOST: /run/secrets/virtual
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: /run/secrets/letsencrypt
      LETSENCRYPT_EMAIL: /run/secrets/letsencrypt_email
      TOKEN: /run/secrets/token
    secrets:
      - "virtual"
      - "letsencrypt"
      - "token"
      - "letsencrypt_email"
secrets:
  virtual:
    file: ./secrets/virtual_host.txt
  letsencrypt:
    file: ./secrets/letsencrypt_host.txt
  token:
    file: ./secrets/token.txt
  letsencrypt_email:
    file: ./secrets/letsencrypt_email.txt