name: deployment

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.USER }}
            server: ${{ secrets.HOST }}
            port: ${{ secrets.PORT }}
            local_path: './'
            remote_path: './docker'
            sftp_only: true
            password: ${{ secrets.PASSWORD }}
