name: Docker Image CI

on:
  workflow_run:
    workflows: [Build and test]
    types: [completed]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: thestephenhunt/flashy:latest
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/docker;docker stop docker-server-1;docker rm docker-server-1;docker pull thestephenhunt/flashy:latest;docker-compose up -d
